### PR TITLE
adjustment variable.scss

### PR DESCRIPTION
**Pull request by PhilharmonicHsu**
@Izushi @chu-pei-ning PTAL

1. I just found we need to add '_' in front of `variable.scss` 
2. Changed the value of `$h1-font-family`

### CODE REVIEW

**Comment by chu-pei-ning** [comment]
PTAL

**Comment by chu-pei-ning** [comment]
LGDM

**Comment by Izushi** [comment]
LGTM

**Comment by chu-pei-ning** [comment]
LGTM

**Pull request merged**
